### ISSUE TITLE
Still required to use root user to deploy resources

### ISSUE THREAD

**Issue by jim-hill-r** [jim-hill-r/gmby6#1]

**Comment by geryonghost** [comment]
A user with IamMutator role is needed. This super user replaces the majority of root functions. Individual IAM roles can be created for CLI access to deploy project components.

**Comment by jim-hill-r** [comment]
So create a script to create one?

**Comment by geryonghost** [comment]
gmby6/core/infra/provision/start.py creates the IamMutator user. You need to create a new username instead of using your "personal" IAM user.

**Comment by jim-hill-r** [comment]
As far as I understand IAM, each human should only have a single User login and then IAM gives ROLE permissions to that user, so I would assume a role once logged in giving me additional permissions. I don't want multiple users credentials to manage.

**Comment by geryonghost** [comment]
This is true. Just like the root account, the primary sub-account for 100%
admin access should be shared among a collection of members.

I will try and script your IAM access to include the ability to do your
tasks. It is hard though without the immediate ability for trial and error.

*Steven Hill*
Secured by Skygate Security

**Comment by geryonghost** [comment]
Created IAM Groups and assigned users to groups.
