### ISSUE TITLE
Users can't authenticate

### ISSUE THREAD

**Issue by jim-hill-r** [jim-hill-r/gmby6#4]
- [x] Create cognito service to host user database. It should be named gmby6-users
- [x] Create route for /signin which redirects to cognito
- [x] Create route for /login which is the callback from cognito and handles auth code by requesting a token
- [x] Call cognito /token to get user jwt token from authorization code
- [x] Create sidebar "signin" link to route to /signin.
- [x] Create sidebar "signout" link to route to /signout when already logged in

**Comment by geryonghost** [comment]
Script created for the creation of Cognito User Pool.

**Comment by jim-hill-r** [comment]
Blocked on Jim training Steven on how to commit code.

**Comment by geryonghost** [comment]
Cognito Userpool: Created
Cognito App Client: Created
Cognito Login URL: Created
https://6umby.auth.us-east-2.amazoncognito.com/login?client_id=7cbcn9b7fbrva8c3lua61p0bma&response_type=code&scope=email+openid&redirect_uri=https://www.6umby.com/callback.html

This is using authorization code grant requiring a token endpoint. https://docs.aws.amazon.com/cognito/latest/developerguide/token-endpoint.html
