### ISSUE TITLE
www.6umby.com traffic through to s3 may be insecure

### ISSUE THREAD

**Issue by jim-hill-r** [jim-hill-r/gmby6#8]
Everything is implemented. Need to do security audit and validation that configuration is correct for end to end behavior. Traffic coming in through the internet via www.6umby.com should be secure. There should be no other way to hit the s3 resources other than this domain.

**Comment by geryonghost** [comment]
Steps via the UI have been created. Coding the solution seems excessive versus updating via UI and coding a rebuild as backup.

**Comment by jim-hill-r** [comment]
Could you describe the steps? The goal is to have Idempotent scripts that produce the correct configuration. If there is best practices for audit, can we script them to ensure we don't accidentally break something?

**Comment by geryonghost** [comment]
[Create UserPool.txt](https://github.com/jim-hill-r/gmby6/files/3996100/Create.UserPool.txt)

Here is the basic code to create a userpool within Cognito. Then all transactions should be via the site.

**Comment by geryonghost** [comment]
Cloudfront

Created Origin access identity
Created Origin (S3-gmby6-app2)
Altered behaivor to point at S3-gmby6-app2
Deleted Origin (S3-gmby6-app)
Created Origin (S3-gmby6-app)
Altered behaivor to point at S3-gmby6-app
Added Default Root Object

S3
Block all public access ON
ACL
	Added Canonical ID for new Origin access identity
Bucket Policy
{
    "Version": "2008-10-17",
    "Id": "PolicyForCloudFrontPrivateContent",
    "Statement": [
        {
            "Sid": "1",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity [UNIQUE ID HERE]"
            },
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::gmby6-app/*"
        }
    ]
}
